Bbs 01 index.html
HummerHead87/Barbershop-Borodinski pull request #2
Opened 2016-12-24 14:10 UTC by HummerHead87

2016-12-26 09:07 UTC, saintgeo23 requested changes
замечания, которые не получилось приписать конкретным строкам:

1. попробовать уйти от конкретных именований классов, завязанных на реализации (comments, comments-and-subscribe, advantage, news-and-photo) и сменить их на более общие ничего не значащие (infoblock, metablock, infoframe и т.п.)
блоки, которые ведут себя похоже объединять классом и отличать через модификатор

2. картинки кнопок соц-сетей сейчас имеют фон
а что если дизайн чуть поменяется? будешь вырезать из макета кнопку с новым цветом фона?
вырезать только значок - остальное - силами css

3. зачем тебе спрайт, если есть отдельные картинки соц-сетей?
оставь их и убери спрайт

4. какие-то бинарники пролезли в пулл-реквест
удали

а в целом - ты молодчага!
очень здорово!
я думал, замечаний будет больше.
почти все замечания основаны только на отсутствии у тебя должного опыта, а не на невнимательности
молодец!

правь и присылай опять на проверку 

# Ответ

Не знаю куда ответить на этот пост напишу здесь.

1. Пофиксил;

2. Пофиксил. В фотошопе были скрыты эффекты для кнопок футера. Постарался реализовать их силами CSS;

3. Забыл удалить отдельные картинки. Я их нарезал только для того чтобы сделать спрайт. Обновил спрайт. Теперь там 6 маленьких иконок. Отдельные картинки удалил.

4. Это файлы web шрифтов, которые шли вместе с макетом. Они подключены через @font-face с ссылкой на локальную папку. Если их удалить оттуда браузер не будет подгружать их с хоста.

Спасибо за отзыв!

P.S. инлайновые стили для картинок не стал удалять следуя рекомендациям [htmlacademy](https://htmlacademy.ru/courses/104/run/10):

> Указывая размеры картинок в атрибутах (и не просто размеры, а настоящие размеры картинок) мы помогаем браузерам быстрее и эффективнее отрисовывать наши страницы. Если браузер знает размеры картинки из HTML-кода, то он может выделить место под неё на странице ещё до загрузки картинки. А когда такая картинка загрузится, браузеру не придётся заново перерисовывать всю страницу.

Мб эти требования уже устарели, все таки скоростной интернет сейчас даже в деревнях есть. Только геморой лишний, если вдруг понадобится переопределить через CSS. Но там только у лого и фото размеры определены инлайновыми стилями. Эти свойства мне кажется редко меняются.

2016-12-26 09:07 UTC, saintgeo23 commented on index.html
> +                    <input class="button button_size-l button_theme-dark" type="text" value="Отправить">
`type="submit"`

2016-12-26 09:07 UTC, saintgeo23 commented on index.html
> +                    <input class="button button_size-l button_theme-dark" type="text" value="Отправить">
иначе можно сделать вот так
http://take.ms/bS79P

2016-12-26 09:07 UTC, saintgeo23 commented on blocks/advantage/advantage.css
> +.advantage__p {
тут наименование должно быть что-то типа `.advantage__text` или `.advantage__label`

2016-12-26 09:07 UTC, saintgeo23 commented on blocks/advantage/advantage.css
> +    filter: drop-shadow(0 0 1px #a7a5a3);
Сравнение поддержки filter и box-shadow
http://take.ms/n4IUU
все-таки для тени лучше юзать box-shadow

2016-12-26 09:07 UTC, saintgeo23 commented on blocks/advantage/advantage.css
> +}
в конце каждого файла должна быть пустая строка.
установи в редактор какой-нибудь линтер (загугли, если слышишь впервые) кода.
и он тебе сам это будет делать при сохранении

2016-12-26 09:07 UTC, saintgeo23 commented on blocks/advantages/advantages.css
> +.advantages {
вообще это все лучше запихнуть в advantage
а каждый анвантадж в отдельности будет `.advantage__item`

2016-12-26 09:07 UTC, saintgeo23 commented on css/styles.css
> +}
учитывая обилие апперкейс, я бы дал сюда `text-transform: uppercase`
а конкретно там где это не нужно - `text-transform: none`

2016-12-26 09:07 UTC, saintgeo23 commented on blocks/button/button.css
> +    font-weight: bold;
зачем font-family? в body же описано правило
и font-size у тебя тут 2 раза

2016-12-26 09:07 UTC, saintgeo23 commented on blocks/button/button.css
> +.button_theme-dark {
а что, есть баттоны не с черным фоном?
прописывай в `.button`
а если появится кнопка с другим фоном, введешь модификатор для другого фона

2016-12-26 09:07 UTC, saintgeo23 commented on blocks/contacts-and-subscribe/contacts-and-subscribe.css
> +.contacts-and-subscribe {
лучше не завязывать названия на функционале
какой-нибудь `.metablock`

2016-12-26 09:07 UTC, saintgeo23 commented on blocks/contacts/contacts.css
> +.contacts__container {
элемент без блока? так не бывает
лучше блок пустым сделать
```
.contacts {
}

.contacts__container {
  ...
}
```

2016-12-26 09:07 UTC, saintgeo23 commented on blocks/footer/footer.css
> +    padding-bottom: 46px;
`padding: 58px 0 46px;`

2016-12-26 09:07 UTC, saintgeo23 commented on blocks/footer/footer.css
> +    color: white;
неконсистентно: где-то пишешь #ffffff, а где-то white
нужно выбрать что-то одно

2016-12-26 09:07 UTC, saintgeo23 commented on blocks/footer/footer.css
> +    left: 0;
сейчас багов нет, но для мозиллы нужно описывать 2 координаты
иначе можно нарваться на самодеятельность браузера

2016-12-26 09:07 UTC, saintgeo23 commented on blocks/footer/footer.css
> +.footer__contacts {
```
.footer__item {
  position: absolute;
  top: 0;
}

.footer__item_left {
  left: 0;
}
```

2016-12-26 09:07 UTC, saintgeo23 commented on blocks/footer/footer.css
> +.footer__copyright {
```
.footer__item_right {
  right: 0;
}
```

2016-12-26 09:07 UTC, saintgeo23 commented on blocks/footer/footer.css
> +    filter: invert(1);
перепиши без фильтра

2016-12-26 09:07 UTC, saintgeo23 commented on blocks/form-subscribe/form-subscribe.css
> +.form-subscribe__input {
сперва
```
.form {
}
```

2016-12-26 09:07 UTC, saintgeo23 commented on blocks/form-subscribe/form-subscribe.css
> +    font-weight: bold;
а точно обязательно все эти правила повторять
font-size, line-height, font-weight?

2016-12-26 09:07 UTC, saintgeo23 commented on blocks/h1/h1.css
> +.h1 {
`.title`

2016-12-26 09:07 UTC, saintgeo23 commented on blocks/header/header.css
> +.header__nav {
`.header__item_left`

2016-12-26 09:07 UTC, saintgeo23 commented on blocks/header/header.css
> +.header__signin {
`.header__item_right`

2016-12-26 09:07 UTC, saintgeo23 commented on blocks/header/header.css
> +.header__button-active .header__button-text {
желательно использовать `>` там где это возможно
и
`.header__button.is-active`
класс is-active мы потом JSом будем навешивать

2016-12-26 09:07 UTC, saintgeo23 commented on blocks/header/header.css
> +.header__button_style-signin {
переработай как-нибудь название на более общее

2016-12-26 09:07 UTC, saintgeo23 commented on blocks/link/link.css
> +.link_theme-light {
```
.link {
}
```

2016-12-26 09:07 UTC, saintgeo23 commented on blocks/logo/logo.css
> +.logo__img {
`.logo__image`

2016-12-26 09:07 UTC, saintgeo23 commented on blocks/section/section.css
> +.section__p {
поменяй название

2016-12-26 09:07 UTC, saintgeo23 commented on blocks/section/section.css
> +.section__news {
опять же юзай __item

2016-12-26 09:07 UTC, saintgeo23 commented on blocks/social/social.css
> +    display: inline-block;
блокам с `display: inline-block;` обязательно нужно давать `vertical-align` какой-нибудь (top, bottom, middle)
иначе каждый браузер поставит свой  `baseline` и будет везде по-разному

2016-12-26 09:07 UTC, saintgeo23 commented on blocks/social/social.css
> +.social+.social {
вот тут у тебя структура не вяжется
.social нужно было сделать контейнером, а в нем уже инлайн-блоки .social__item
`.social__item + .social__item`

2016-12-26 09:07 UTC, saintgeo23 commented on blocks/wrapper/wrapper.css
> +.wrapper__container {
```
.wrapper {
}
```

2016-12-26 09:07 UTC, saintgeo23 commented on css/styles.css
> +}
и font-family сюда лучше из body перенести
тогда его везде не придется указывать

2016-12-26 09:07 UTC, saintgeo23 commented on index.html
> +            <nav class="nav">
лучше .navigation

2016-12-26 09:07 UTC, saintgeo23 commented on index.html
> +            <img src="blocks/logo/logo__img.png" alt="Barbershop BORODINSKI" width="368" height="204">
где класс?
что за инлайновые стили?
поправить

можешь убрать вышестоящий див и его класс и стили написать сюда

ничего страшного в img display: block нет

2016-12-26 09:07 UTC, saintgeo23 commented on index.html
> +                <h2 class="advantage__header h1">Быстро</h2>
мощно
h2 с классом h1
сам себя запутать хотел?)

2016-12-26 09:07 UTC, saintgeo23 commented on index.html
> +                    <h2 class="h1">Новости</h2>
h2 h1 снова

2016-12-26 09:07 UTC, saintgeo23 commented on index.html
> +                <h2 class="h1">Фотогалерея</h2>
и тут

2016-12-26 09:07 UTC, saintgeo23 commented on index.html
> +                    <a href="#">
где класс? 
оставляешь стили на усмотрение браузерам?

2016-12-26 09:07 UTC, saintgeo23 commented on index.html
> +                        <img class="section__photo" src="blocks/section/section__photo.jpg" alt="Photo" width="286" height="164">
инлайн стили опять

2016-12-26 09:07 UTC, saintgeo23 commented on index.html
> +                    <h2 class="h1">Контактная информация</h2>
h2 h1

2016-12-26 09:07 UTC, saintgeo23 commented on index.html
> +                <a class="button button_size-m button_theme-dark section__buttons" href="#">Как проехать</a>
чтобы тебе не перезагружало страницу и не скакало по ней, можно в качестве href ставить `href="javascript:;"`

2016-12-26 09:07 UTC, saintgeo23 commented on index.html
> +                <h2 class="h1">Записаться</h2>
h2 h1

2016-12-26 18:01 UTC, HummerHead87 commented on index.html
> +                    <input class="button button_size-l button_theme-dark" type="text" value="Отправить">
упс, опечатка ))

2016-12-26 18:29 UTC, HummerHead87 commented on index.html
> +            <nav class="nav">
fixed

2016-12-26 18:29 UTC, HummerHead87 commented on index.html
> +            <img src="blocks/logo/logo__img.png" alt="Barbershop BORODINSKI" width="368" height="204">
fixed

2016-12-26 18:30 UTC, HummerHead87 commented on index.html
> +                <h2 class="advantage__header h1">Быстро</h2>
fixed

2016-12-26 18:30 UTC, HummerHead87 commented on index.html
> +                    <h2 class="h1">Новости</h2>
fixed

2016-12-26 18:30 UTC, HummerHead87 commented on index.html
> +                <h2 class="h1">Фотогалерея</h2>
fixed

2016-12-26 18:37 UTC, HummerHead87 commented on index.html
> +                        <img class="section__photo" src="blocks/section/section__photo.jpg" alt="Photo" width="286" height="164">
[htmlacademy.ru](url("https://htmlacademy.ru/courses/104/run/10")) рекомендует указывать ширину и высоту в инлайн стилях для изображений. 

> Указывая размеры картинок в атрибутах (и не просто размеры, а настоящие размеры картинок) мы помогаем браузерам быстрее и эффективнее отрисовывать наши страницы. Если браузер знает размеры картинки из HTML-кода, то он может выделить место под неё на странице ещё до загрузки картинки. А когда такая картинка загрузится, браузеру не придётся заново перерисовывать всю страницу.

2016-12-26 18:41 UTC, HummerHead87 commented on index.html
> +                    <a href="#">
ну хз. Там и стиля-то в-общем никакого нет. Просто сделал из картинки ссылку, по типу как в галерее, когда при клике на картинке выскакивает popup с увеличенным размером.

2016-12-26 18:41 UTC, HummerHead87 commented on index.html
> +                    <h2 class="h1">Контактная информация</h2>
fixed

2016-12-26 18:43 UTC, HummerHead87 commented on index.html
> +                <a class="button button_size-m button_theme-dark section__buttons" href="#">Как проехать</a>
fixed

2016-12-26 18:44 UTC, HummerHead87 commented on index.html
> +                <h2 class="h1">Записаться</h2>
fixed

2016-12-26 18:44 UTC, HummerHead87 commented on index.html
> +                    <input class="button button_size-l button_theme-dark" type="text" value="Отправить">
fixed

2016-12-26 18:50 UTC, HummerHead87 commented on blocks/advantage/advantage.css
> +    filter: drop-shadow(0 0 1px #a7a5a3);
box-shadow не подойдет в данном случае, т.к. он задает тень блоку, а drop-shadow задает тень для контуров изображения. Иначе получается совсем другой результат: http://take.ms/RYtG2

2016-12-26 18:54 UTC, HummerHead87 commented on blocks/advantage/advantage.css
> +    filter: drop-shadow(0 0 1px #a7a5a3);
box-shadow не подходит в данном случае, т. к. тень задается контурам изображения, а box-shadow создаст тень для блока: https://monosnap.com/file/bNSS4WosRgzfjVu3vnGc58pNJoRljH

2016-12-26 18:55 UTC, HummerHead87 commented on blocks/advantage/advantage.css
> +}
fixed

2016-12-26 18:57 UTC, HummerHead87 commented on blocks/advantage/advantage.css
> +.advantage__p {
fixed

2016-12-26 19:16 UTC, HummerHead87 commented on blocks/advantages/advantages.css
> +.advantages {
fixed

2016-12-26 19:23 UTC, HummerHead87 commented on blocks/button/button.css
> +    font-weight: bold;
из body не наследовались свойства шрифта для input[type="submit"] поэтому продублировал.
После того как прописал свойства в * { } заработало и для submit.

2016-12-26 19:23 UTC, HummerHead87 commented on blocks/button/button.css
> +    font-weight: bold;
fixed

2016-12-26 19:26 UTC, HummerHead87 commented on blocks/button/button.css
> +.button_theme-dark {
Протупил. Создал в хедере кнопки без фона,  а в остальных местах с черным фоном, хотя можно и для хедера черный фон задать.

2016-12-26 19:26 UTC, HummerHead87 commented on blocks/button/button.css
> +.button_theme-dark {
fixed

2016-12-29 07:51 UTC, saintgeo23 requested changes
Совсем немного замечаний

2016-12-29 07:51 UTC, saintgeo23 commented on blocks/header/header.css
> +header__item {}
опечатка

2016-12-29 07:51 UTC, saintgeo23 commented on blocks/section/section.css
> +.section_type-right {
модификаторы самого блока идут сразу после него, только потом элементы и их модификаторы

2016-12-29 07:51 UTC, saintgeo23 commented on index.html
> +
советую еще добавить `<meta name="viewport" content="width=device-width, initial-scale=1">`

2016-12-29 07:51 UTC, saintgeo23 commented on index.html
> +
заодно почитай про него

2016-12-29 07:51 UTC, saintgeo23 commented on index.html
> +                <p class="infoblock__label">МЫ ДЕЛАЕМ СВОЮ РАБОТУ БЫСТРО! ДВА ЧАСА ПРОЛЕТЯТ НЕЗАМЕТНО И ВЫ — СЧАСТЛИВЫЙ ОБЛАДЕТЕЛЬ СТИЛЬНОЙ СТРИЖКИ-МИНУТКИ!</p>
зачем тебе капс если у тебя `* { text-transform: uppercase; }`?

2016-12-29 19:05 UTC, merged