Bbs 02
HummerHead87/Barbershop-Borodinski pull request #3
Opened 2017-01-08 18:24 UTC by HummerHead87

2017-01-10 12:22 UTC, saintgeo23 requested changes
Поправок, в принципе, немного, ты молодчина!
Немного дегтя:
1. комментарии убирай в цсс-файлах, если не нужны. по сути, pull-request это такое состояние кода, когда ты уже готов отправить его в продакшен. а зачем тебе там лишние комментарии?
2. не делай много модификаторов, если это возможно, давай какие-то значения по дефолту, а уже меняй их по модификаторам.
3. никакого debug.log в репозитории быть не должно
отправляй его в .gitignore файл
4. пустые строки в конце файлов не забывай.
5. сделал ПР, сам посмотри его, кое-что можешь и заметить сам
6. все символы заменять на их код
я тут смотрю - http://paulradzkov.com/2012/html-entities_and_utf_codes/

вообще - молодец, я в это же время такой шлак писал - страшно вспомнить)))

2017-01-10 12:22 UTC, saintgeo23 commented on blocks/button/button.css
> +.button_allocated+.button_allocated {
пробелы вокруг плюса

2017-01-10 12:22 UTC, saintgeo23 commented on blocks/button/button.css
> +.button_allocated+.button_allocated {
везде

2017-01-10 12:22 UTC, saintgeo23 commented on blocks/input/input.css
> +.input__input {
странно смотрится
мож лучше .input__field?

2017-01-10 12:22 UTC, saintgeo23 commented on blocks/input/input.css
> +    content: "●";
```
content: "&bull;";
```

2017-01-10 12:22 UTC, saintgeo23 commented on blocks/product/product.css
> +}
объединяешь этот и верхний в один блок и потом конкретизируешь ниже разные left

2017-01-10 12:22 UTC, saintgeo23 commented on blocks/product/product.css
> +}
это чтобы не было копипасты

2017-01-10 12:22 UTC, saintgeo23 commented on blocks/section/section.css
> +}
можешь имаджу дать какие-то размеры, а другие уже делать модификатором

2017-01-10 12:22 UTC, saintgeo23 commented on blocks/section/section.css
> +}
наверно лучше маленькие, ведь таких имаджей больше на странице, поэтому выгодней будет

2017-01-10 12:22 UTC, saintgeo23 commented on index.html
>              <form class="form" action="#" method="POST">
сюда тоже в экшн лучше ставить javascript:;

2017-01-10 12:22 UTC, saintgeo23 commented on index.html
>              <form class="form" action="#" method="POST">
ну пока нет реального экшна в смысле

2017-01-10 12:22 UTC, saintgeo23 commented on price.html
> +                    Цены на услуги<br> наших мастеров:
зачем пробел?

2017-01-10 12:22 UTC, saintgeo23 commented on price.html
> +</html>
пустая строка

2017-01-10 12:22 UTC, saintgeo23 commented on shop.html
> +                <span class="link">Магазин</span>
почему здесь спан? сделай ссылку, пусть никуда не ведет, но тут должна быть ссылка.
в хлебных крошках только последний пункт неактивен

2017-01-10 12:22 UTC, saintgeo23 commented on shop.html
> +                                <label class="input__label input__label_checkbox" for="item2">Mr Natty</label>
можно делать через id/for, но потом ты эти вещи будешь делать через шаблонизатор и будет сложно ставить такие вещи как item2, item3 и т.д., потому что эти списки будут составляться динамически
оборачивай инпут в лейбл

2017-01-10 12:22 UTC, saintgeo23 commented on shop.html
> +                            <img class="product__image" src="./blocks/product/product__image_conditioner-baxter.jpg" alt="Увлажняющий кондиционер «Baxter of California»" width="220" height="165">
```
alt="Увлажняющий кондиционер &laquo;Baxter of California&raquo;"
```

2017-01-10 12:22 UTC, saintgeo23 commented on shop.html
> +                            <div class="product__label_type">Набор для путешествий</div>
напишу только тут, но поправить нужно везде: в строчные элементы (a, span) нельзя помещать блочные, это моветон и плохо для SEO, меняй на спаны и давай им display: block тогда

2017-01-10 12:22 UTC, saintgeo23 commented on shop.html
> +                            <img class="product__image" src="./blocks/product/product__image_conditioner-baxter.jpg" alt="Увлажняющий кондиционер «Baxter of California»" width="220" height="165">
и везде так

2017-01-10 19:09 UTC, HummerHead87 commented on blocks/button/button.css
> +.button_allocated+.button_allocated {
linter что-то чудит. Не дает так сохранять. Буду разбираться

2017-01-10 19:13 UTC, HummerHead87 commented on blocks/input/input.css
> +.input__input {
fixed

2017-01-10 19:29 UTC, HummerHead87 commented on blocks/input/input.css
> +    content: "●";
fixed "\0025CF"

2017-01-10 19:45 UTC, HummerHead87 commented on blocks/product/product.css
> +}
решил переделать немного. Засунул эти элементы в flex-box, которому задал абсолютное позиционирование и координаты bottom: 16px и по центру Y. А эти модификаторы удалил

2017-01-10 19:46 UTC, HummerHead87 commented on blocks/product/product.css
> +}
`.product__container_buy {
    position: absolute;
    bottom: 16px;
    left: 50%;
    transform: translateX(-50%);
}`

2017-01-10 19:46 UTC, HummerHead87 commented on blocks/product/product.css
> +}
fixed

2017-01-10 19:57 UTC, HummerHead87 commented on blocks/section/section.css
> +}
Задал для section__image размеры как у картинки в блоке фото на index.html.

2017-01-10 19:58 UTC, HummerHead87 commented on index.html
>              <form class="form" action="#" method="POST">
fixed

2017-01-10 20:00 UTC, HummerHead87 commented on price.html
> +                    Цены на услуги<br> наших мастеров:
fixed

2017-01-10 20:00 UTC, HummerHead87 commented on price.html
> +</html>
Настроил linter для html

2017-01-10 20:01 UTC, HummerHead87 commented on price.html
> +</html>
fixed

2017-01-10 20:03 UTC, HummerHead87 commented on shop.html
> +                <span class="link">Магазин</span>
fixed

2017-01-10 20:24 UTC, HummerHead87 commented on shop.html
> +                                <label class="input__label input__label_checkbox" for="item2">Mr Natty</label>
у меня тогда перестает работать визуальное оформление, т.к. селектор `.input__field:checked+.input__label_checkbox::before` уже не подходит

2017-01-10 21:19 UTC, saintgeo23 commented on shop.html
> +                                <label class="input__label input__label_checkbox" for="item2">Mr Natty</label>
соглашусь!
оставь так

2017-01-11 17:25 UTC, HummerHead87 commented on shop.html
> +                            <div class="product__label_type">Набор для путешествий</div>
fixed

2017-01-11 17:29 UTC, HummerHead87 commented on shop.html
> +                            <img class="product__image" src="./blocks/product/product__image_conditioner-baxter.jpg" alt="Увлажняющий кондиционер «Baxter of California»" width="220" height="165">
fixed

2017-01-12 07:27 UTC, saintgeo23 approved these changes

2017-01-12 18:15 UTC, merged

2017-01-12 18:20 UTC, saintgeo23 commented
+ это не оператор, это селектор

2017-01-12 18:21 UTC, saintgeo23 commented
маркап заменил
я писал про `+`

2017-01-12 18:25 UTC, HummerHead87 commented
хм. А я все настройки линтера уже прошерстил в поисках space after between operators и нифига не нашел. А это оказывается селектор ))